### ISSUE TITLE
Community Chat

### ISSUE THREAD

**Issue by wcrum** [hauler-dev/hauler-docs#24]
As Hauler moved from RGS org to hauler-dev, I believe there was a Hauler slack inside rancher-users.slack.com. Is it planned to have a separate slack or group to chat within?

Docousarus docs config still references rancher-users.slack.com.

**Comment by zackbradys** [comment]
Thank you for pinging us about this... definitely overdue! 

`#hauler` has been created in `rancher-users` --> https://rancher-users.slack.com/archives/C07F009GNRY
